name: PHP Syntax Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # ou '8.1' si tu préfères

    - name: Lint PHP files
      run: find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;
